#!/bin/sh
echo tags update for $PWD
ctags -f ~/.tags/tags --fields=+l --c-kinds=+p --c++-kinds=+p --extra=+q -R $PWD 
ctags -a -f ~/.tags/tags --fields=+l --c-kinds=+p --c++-kinds=+p --extra=+q -R /usr/include/ 
ctags -a -f ~/.tags/tags --fields=+l --c-kinds=+p --c++-kinds=+p --extra=+q -R /usr/local/include/ 
